(: A Type)
(a A)
!(a b (+ 2 3) )


; Prints [5]
(= f 5)
(= (g) p)
(= h (a))
!(match &self (= f $t) $t)
!(f)
! -g-
!(g) ; Value of (g) is printed without using match. But you need to put it
;inside braces in the definition it has in the equlaity expression it appears in.

;; (= f $r)
! f
f
! g
! h
! (h)
;;

; Prints [((= e $t) $t)]
(= a 5)
(= b 5)
(= e (* a b))

!(match &self (= e $t) $t)

;;

!(= g $s)

;;

!(+ 2 3)

;;

(= (a b) c)
(= c 6)

((d e) f)

;; (= (a b) $r)
!(a b)

!(= (a b) $r)
!(match &self (= ($x $y) c) $x)

!(match &self (($x $y) f) $x)
!(d e)

